name: math_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.13
  youtube_player_flutter: ^8.1.2
  splashscreen: ^1.3.5
  http: ^0.13.5
  get_storage: ^2.1.1
  im_stepper: ^1.0.1+1
  flutter_html: ^2.1.2
  photo_view: ^0.14.0
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/games/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
